---
# This is the environment YML file, the values in this file are intended to be replaced
# by the azure build / release infrastructure
#
# Naming standards pulled from: 
# https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/resource-abbreviations
#

default_tags:
  stage: "{{ stage }}"
  application: "{{ application }}"

# Azure authorization Source
auth_source: cli

resource_group: 
  name: rg-{{ stage }}-{{ application }}
  region: "{{ region }}"
  tags: "{{ default_tags }}"

key_vault:
  name: kv-{{ stage }}-{{ application }}
  tenant: "{{ tenant_id }}"
  owner: "{{ owner_id }}"
  region: "{{ region }}"
  tier: standard
  tags: "{{ default_tags }}"

app_service_plan:
  name: plan-{{ stage }}-{{ application }}
  region: "{{ region }}"
  workers: 1
  os: Linux
  sku: B1
  tags: "{{ default_tags }}"

api_app:
  name: app-api-{{ stage }}-{{ application }} 
  region: "{{ region }}"
  is_custom_domain: false #*.azurewebsites.net
  #custom_domain: ... #.mywebsite.com
  ssl_enabled: true
  runtime: dotnetcore
  runtimeVersion: 5.0
  executable: StarWars.Api.dll
  tags: "{{ default_tags }}"

web_app:
  name: app-web-{{ stage }}-{{ application }} 
  region: "{{ region }}"
  is_custom_domain: false #*.azurewebsites.net
  #custom_domain: ... #.mywebsite.com
  ssl_enabled: true
  runtime: dotnetcore
  runtimeVersion: 5.0
  executable: StarWars.Web.dll
  tags: "{{ default_tags }}"

function_app:
  name: func-{{ stage }}-{{ application }}
  region: "{{ region }}"
  tags: "{{ default_tags }}"
  
storage_account:
  name: st{{ stage }}{{ application}}
  region: "{{ region }}"
  tier: Hot
  account_type: Standard_LRS 
  tags: "{{ default_tags }}"

log_analytics:
  name: log-{{ stage }}-{{ application }}
  region: "{{ region }}"
  tier: per_gb2018
  tags: "{{ default_tags }}"

app_insights:
  name: appi-{{ stage }}-{{ application }}
  region: "{{ region }}"
  type: web
  tags: "{{ default_tags }}"

... #End Doc
