---
# tasks file for webapp

- name: Create App
  azure_rm_webapp:
    name: "{{ api_app['name'] }}"
    app_state: started
    frameworks:
      - name: "{{ api_app['runtime'] }}"
        version: "{{ api_app['runtimeVersion'] }}"
    https_only: "{{ api_app['ssl_enabled'] }}"
    plan: "{{ app_service_plan['name'] }}"
    purge_app_settings: no
    skip_custom_domain_verification: yes
    startup_file: "dotnet {{ api_app['executable']}}"
    location: "{{ api_app['region'] }}"
    resource_group: "{{ resource_group['name'] }}"
    auth_source: "{{ auth_source }}"
    tags: "{{ api_app['tags'] }}"
    append_tags: false
    state: present
  register: apiapp

- debug:
    var: apiapp
    verbosity: 2
