---
# tasks file for webapp
- name: Create App
  azure_rm_webapp:
    name: "{{ web_app['name'] }}"
    app_state: started
    frameworks:
      - name: "{{ web_app['runtime'] }}"
        version: "{{ web_app['runtimeVersion'] }}"
    https_only: "{{ web_app['ssl_enabled'] }}"
    plan: "{{ app_service_plan['name'] }}"
    purge_app_settings: no
    skip_custom_domain_verification: yes
    startup_file: "dotnet {{ web_app['executable']}}"
    location: "{{ web_app['region'] }}"
    resource_group: "{{ resource_group['name'] }}"
    auth_source: "{{ auth_source }}"
    tags: "{{ web_app['tags'] }}"
    append_tags: false
    state: present
  register: webapp

- debug:
    var: webapp
    verbosity: 2
