---
- hosts: localhost
  connection: local
  vars:
    - stage: "test"
    - application: "securegqldemo"
    - region: "eastus2"

  vars_files:
    - vars/environment.yml
    - vars/vars.{{stage}}.yml

  roles:
    - base
    - apiapp
#    - funcapp
#    - webapp
